// Run with PGlite installed in /tmp/todago-audit. No live project is contacted.
import { PGlite } from '/tmp/todago-audit/node_modules/@electric-sql/pglite/dist/index.js';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';

const db = new PGlite();
await db.exec(`
  create role authenticated;
  create role anon;
  create role service_role;
  create schema auth;
  create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('test.uid', true), '')::uuid $$;
  create function auth.jwt() returns jsonb language sql as $$ select '{"user_metadata":{"role":"admin"}}'::jsonb $$;
  create type public.user_role as enum ('passenger', 'driver', 'admin');
  create table profiles(id uuid primary key, role user_role, is_active boolean default true, first_name text, last_name text, full_name text, phone_number text, email text, updated_at timestamptz);
  create table passengers(id uuid primary key, profile_id uuid unique, cancel_count int default 0, last_cancel_date timestamptz, warning_status boolean default false, booking_restriction_until timestamptz, discount_document_status text default 'VERIFIED', updated_at timestamptz);
  create table drivers(id uuid primary key, profile_id uuid);
  create table vehicles(id uuid primary key);
  create table bookings(id uuid primary key, passenger_id uuid, driver_id uuid, status text, trip_phase text, cancelled_by text, cancelled_at timestamptz, cancel_reason text, created_at timestamptz default now(), updated_at timestamptz);
  create table notifications(id uuid primary key default gen_random_uuid(), recipient_id uuid, title text, body text, notification_category text, data jsonb);
  create table booking_discount_requests(id uuid primary key);
  create table driver_profile_change_requests(id uuid primary key);
  create table reports(id uuid primary key);
  create publication supabase_realtime;
  create function current_passenger_id() returns uuid language sql as $$ select id from passengers where profile_id = auth.uid() $$;
  create function current_driver_id() returns uuid language sql as $$ select id from drivers where profile_id = auth.uid() $$;
  create function current_driver_can_view_bookings() returns boolean language sql as $$ select current_driver_id() is not null $$;
`);
await db.exec(await readFile(new URL('../20260909_database_sync_reliability.sql', import.meta.url), 'utf8'));
// Use the repository's existing cancellation-stat trigger implementation.
const bootstrap = await readFile(new URL('../todago_final_bootstrap.sql', import.meta.url), 'utf8');
const start = bootstrap.indexOf('create or replace function public.update_passenger_cancel_stats()');
await db.exec(bootstrap.slice(start, bootstrap.indexOf('$$;', start) + 3));
await db.exec(`create trigger test_cancel_stats after insert or update of status, cancelled_by, passenger_id or delete on bookings for each row execute function update_passenger_cancel_stats();`);

const admin = '00000000-0000-0000-0000-000000000001';
const passenger = '00000000-0000-0000-0000-000000000002';
const driver = '00000000-0000-0000-0000-000000000003';
const stranger = '00000000-0000-0000-0000-000000000004';
const booking = n => `10000000-0000-0000-0000-${String(n).padStart(12, '0')}`;
const asUser = id => db.query("select set_config('test.uid', $1, false)", [id]);
const scalar = async sql => (await db.query(sql)).rows[0];
await db.exec(`
  insert into profiles(id, role) values ('${admin}', 'admin'), ('${passenger}', 'passenger'), ('${driver}', 'driver'), ('${stranger}', 'driver');
  insert into passengers(id, profile_id) values ('${passenger}', '${passenger}');
  insert into drivers(id, profile_id) values ('${driver}', '${driver}'), ('${stranger}', '${stranger}');
`);
await asUser(passenger);
assert.equal((await scalar('select is_admin() as value')).value, false, 'Editable metadata must not grant admin');
await assert.rejects(db.exec(`update profiles set role='admin' where id='${passenger}'`), /Only administrators/);
await assert.rejects(db.exec(`select admin_restrict_passenger('${passenger}', 31)`), /Administrator access/);
await assert.rejects(db.exec(`select admin_lift_passenger_restriction('${passenger}')`), /Administrator access/);
await db.exec(`insert into bookings(id, passenger_id, status) values ('${booking(1)}','${passenger}','searching');`);
await db.exec(`update bookings set status='cancelled', cancelled_by='driver' where id='${booking(1)}'`);
assert.equal((await scalar(`select cancelled_by from bookings where id='${booking(1)}'`)).cancelled_by, 'passenger');
assert.equal((await scalar('select cancel_count from passengers')).cancel_count, 1);
await asUser(admin);
await db.exec(`insert into bookings(id, passenger_id, driver_id, status) values ('${booking(2)}','${passenger}','${driver}','pickedUp');`);
await asUser(passenger);
await assert.rejects(db.exec(`update bookings set status='cancelled' where id='${booking(2)}'`), /Ask your driver/);
await asUser(stranger);
await assert.rejects(db.exec(`update bookings set status='cancelled' where id='${booking(2)}'`), /Only the booking participants/);
await asUser(driver);
await db.exec(`update bookings set status='cancelled' where id='${booking(2)}'`);
assert.equal((await scalar('select cancel_count from passengers')).cancel_count, 1, 'Driver cancellations do not penalize passenger');
assert.equal((await scalar(`select count(*)::int as n from notifications where data->>'booking_id'='${booking(2)}' and notification_category='cancel'`)).n, 2, 'Both accounts receive durable cancellation');
await db.exec(`update bookings set status='cancelled' where id='${booking(2)}'`);
assert.equal((await scalar(`select count(*)::int as n from notifications where data->>'booking_id'='${booking(2)}' and notification_category='cancel'`)).n, 2, 'Repeated state does not duplicate notices');
await asUser(admin);
await db.exec(`select admin_restrict_passenger('${passenger}', 31)`);
assert.equal((await scalar('select cancel_count from passengers')).cancel_count, 1, 'Admin restrictions must not fabricate cancellations');
await asUser(passenger);
await assert.rejects(db.exec(`insert into bookings(id, passenger_id, status) values ('${booking(3)}','${passenger}','searching')`), /restricted/);
await asUser(admin);
await db.exec(`select admin_lift_passenger_restriction('${passenger}')`);
assert.equal((await scalar('select cancel_count from passengers')).cancel_count, 1, 'Lifting restriction preserves history');
await db.exec(`insert into bookings(id, passenger_id, driver_id, status) values ('${booking(4)}','${passenger}','${driver}','completed');`);
await asUser(driver);
await assert.rejects(db.exec(`update bookings set status='cancelled' where id='${booking(4)}'`), /completed booking/);
assert.equal((await scalar(`select get_passenger_public_stats('${passenger}') as stats`)).stats.completed_trips, 1);
await db.close();
console.log('PASS: authorization, cancellation ownership, counts, eligibility, notifications and passenger totals');
